[workspace]
authors = ["nicholasAWwright <nicholas.AW.wright@gmail.com>"]
channels = ["conda-forge"]
name = "task3"
platforms = ["win-64", "linux-64"]
version = "0.1.0"

[tasks]

[dependencies]
python = ">=3.14.0,<3.15"
pillow = ">=12.0.0,<13"
pycryptodome = ">=3.23.0,<4"
jsonschema = ">=4.25.1,<5"

[pypi-dependencies]
volatility3 = ">=2.26.2, <3"
yara-python = ">=4.5.4, <5"


